import { Airline } from '../types/airline';

export const seedAirlines: Omit<Airline, 'id' | 'updatedAt'>[] = [
  {
    iataCode: 'LH',
    icaoCode: 'DLH',
    name: 'Lufthansa',
    country: 'Germany',
    logoUrl: null,
    registrationUrl: 'https://www.lufthansa.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 30,
    notes: null,
  },
  {
    iataCode: 'LO',
    icaoCode: 'LOT',
    name: 'LOT Polish Airlines',
    country: 'Poland',
    logoUrl: null,
    registrationUrl: 'https://www.lot.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 36,
    notes: null,
  },
  {
    iataCode: 'FR',
    icaoCode: 'RYR',
    name: 'Ryanair',
    country: 'Ireland',
    logoUrl: null,
    registrationUrl: 'https://www.ryanair.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'W6',
    icaoCode: 'WZZ',
    name: 'Wizz Air',
    country: 'Hungary',
    logoUrl: null,
    registrationUrl: 'https://wizzair.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'AF',
    icaoCode: 'AFR',
    name: 'Air France',
    country: 'France',
    logoUrl: null,
    registrationUrl: 'https://www.airfrance.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 30,
    notes: null,
  },
  {
    iataCode: 'BA',
    icaoCode: 'BAW',
    name: 'British Airways',
    country: 'United Kingdom',
    logoUrl: null,
    registrationUrl: 'https://www.britishairways.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'KL',
    icaoCode: 'KLM',
    name: 'KLM Royal Dutch Airlines',
    country: 'Netherlands',
    logoUrl: null,
    registrationUrl: 'https://www.klm.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 30,
    notes: null,
  },
  {
    iataCode: 'U2',
    icaoCode: 'EZY',
    name: 'easyJet',
    country: 'United Kingdom',
    logoUrl: null,
    registrationUrl: 'https://www.easyjet.com/en/check-in',
    supportPhone: '',
    checkInHoursBefore: 720,
    notes: null,
  },
  {
    iataCode: 'IB',
    icaoCode: 'IBE',
    name: 'Iberia',
    country: 'Spain',
    logoUrl: null,
    registrationUrl: 'https://www.iberia.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'VY',
    icaoCode: 'VLG',
    name: 'Vueling',
    country: 'Spain',
    logoUrl: null,
    registrationUrl: 'https://www.vueling.com/en/check-in',
    supportPhone: '',
    checkInHoursBefore: 72,
    notes: null,
  },
  {
    iataCode: 'LX',
    icaoCode: 'SWR',
    name: 'Swiss International Air Lines',
    country: 'Switzerland',
    logoUrl: null,
    registrationUrl: 'https://www.swiss.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 23,
    notes: null,
  },
  {
    iataCode: 'OS',
    icaoCode: 'AUA',
    name: 'Austrian Airlines',
    country: 'Austria',
    logoUrl: null,
    registrationUrl: 'https://www.austrian.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 47,
    notes: null,
  },
  {
    iataCode: 'SN',
    icaoCode: 'BEL',
    name: 'Brussels Airlines',
    country: 'Belgium',
    logoUrl: null,
    registrationUrl: 'https://www.brusselsairlines.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'AY',
    icaoCode: 'FIN',
    name: 'Finnair',
    country: 'Finland',
    logoUrl: null,
    registrationUrl: 'https://www.finnair.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 36,
    notes: null,
  },
  {
    iataCode: 'SK',
    icaoCode: 'SAS',
    name: 'SAS Scandinavian Airlines',
    country: 'Sweden',
    logoUrl: null,
    registrationUrl: 'https://www.flysas.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 22,
    notes: null,
  },
  {
    iataCode: 'TP',
    icaoCode: 'TAP',
    name: 'TAP Air Portugal',
    country: 'Portugal',
    logoUrl: null,
    registrationUrl: 'https://www.flytap.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 36,
    notes: null,
  },
  {
    iataCode: 'A3',
    icaoCode: 'AEE',
    name: 'Aegean Airlines',
    country: 'Greece',
    logoUrl: null,
    registrationUrl: 'https://en.aegeanair.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'EI',
    icaoCode: 'EIN',
    name: 'Aer Lingus',
    country: 'Ireland',
    logoUrl: null,
    registrationUrl: 'https://www.aerlingus.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'UX',
    icaoCode: 'AEA',
    name: 'Air Europa',
    country: 'Spain',
    logoUrl: null,
    registrationUrl: 'https://www.aireuropa.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'BT',
    icaoCode: 'BTI',
    name: 'airBaltic',
    country: 'Latvia',
    logoUrl: null,
    registrationUrl: 'https://www.airbaltic.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 36,
    notes: null,
  },
  {
    iataCode: 'PS',
    icaoCode: 'AUI',
    name: 'Ukraine International Airlines',
    country: 'Ukraine',
    logoUrl: null,
    registrationUrl: 'https://www.flyuia.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'PQ',
    icaoCode: 'SQP',
    name: 'SkyUp Airlines',
    country: 'Ukraine',
    logoUrl: null,
    registrationUrl: 'https://skyup.aero/my-booking',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: '7W',
    icaoCode: 'WRC',
    name: 'Windrose Airlines',
    country: 'Ukraine',
    logoUrl: null,
    registrationUrl: 'https://windrose.kiev.ua/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'TK',
    icaoCode: 'THY',
    name: 'Turkish Airlines',
    country: 'Turkey',
    logoUrl: null,
    registrationUrl: 'https://www.turkishairlines.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'PC',
    icaoCode: 'PGT',
    name: 'Pegasus Airlines',
    country: 'Turkey',
    logoUrl: null,
    registrationUrl: 'https://www.flypgs.com/en/check-in',
    supportPhone: '',
    checkInHoursBefore: 72,
    notes: null,
  },
  {
    iataCode: 'EK',
    icaoCode: 'UAE',
    name: 'Emirates',
    country: 'United Arab Emirates',
    logoUrl: null,
    registrationUrl: 'https://www.emirates.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'QR',
    icaoCode: 'QTR',
    name: 'Qatar Airways',
    country: 'Qatar',
    logoUrl: null,
    registrationUrl: 'https://www.qatarairways.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'EY',
    icaoCode: 'ETD',
    name: 'Etihad Airways',
    country: 'United Arab Emirates',
    logoUrl: null,
    registrationUrl: 'https://www.etihad.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 30,
    notes: null,
  },
  {
    iataCode: 'FZ',
    icaoCode: 'FDB',
    name: 'flydubai',
    country: 'United Arab Emirates',
    logoUrl: null,
    registrationUrl: 'https://www.flydubai.com/en/check-in',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'LY',
    icaoCode: 'ELY',
    name: 'El Al Israel Airlines',
    country: 'Israel',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'AA',
    icaoCode: 'AAL',
    name: 'American Airlines',
    country: 'United States',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'DL',
    icaoCode: 'DAL',
    name: 'Delta Air Lines',
    country: 'United States',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'UA',
    icaoCode: 'UAL',
    name: 'United Airlines',
    country: 'United States',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'SQ',
    icaoCode: 'SIA',
    name: 'Singapore Airlines',
    country: 'Singapore',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'CX',
    icaoCode: 'CPA',
    name: 'Cathay Pacific',
    country: 'Hong Kong',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'JL',
    icaoCode: 'JAL',
    name: 'Japan Airlines',
    country: 'Japan',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'KE',
    icaoCode: 'KAL',
    name: 'Korean Air',
    country: 'South Korea',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'TG',
    icaoCode: 'THA',
    name: 'Thai Airways',
    country: 'Thailand',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'QF',
    icaoCode: 'QFA',
    name: 'Qantas',
    country: 'Australia',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'NZ',
    icaoCode: 'ANZ',
    name: 'Air New Zealand',
    country: 'New Zealand',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'CI',
    icaoCode: 'CAL',
    name: 'China Airlines',
    country: 'Taiwan',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'BR',
    icaoCode: 'EVA',
    name: 'EVA Air',
    country: 'Taiwan',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'ET',
    icaoCode: 'ETH',
    name: 'Ethiopian Airlines',
    country: 'Ethiopia',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 36,
    notes: null,
  },
  {
    iataCode: 'MS',
    icaoCode: 'MSR',
    name: 'EgyptAir',
    country: 'Egypt',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'AT',
    icaoCode: 'RAM',
    name: 'Royal Air Maroc',
    country: 'Morocco',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 48,
    notes: null,
  },
  {
    iataCode: 'KQ',
    icaoCode: 'KQA',
    name: 'Kenya Airways',
    country: 'Kenya',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 30,
    notes: null,
  },
  {
    iataCode: 'DY',
    icaoCode: 'NOZ',
    name: 'Norwegian',
    country: 'Norway',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'J2',
    icaoCode: 'AHY',
    name: 'Azerbaijan Airlines',
    country: 'Azerbaijan',
    logoUrl: null,
    registrationUrl: 'https://www.azal.az/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'HY',
    icaoCode: 'UZB',
    name: 'Uzbekistan Airways',
    country: 'Uzbekistan',
    logoUrl: null,
    registrationUrl: 'https://www.uzairways.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'T5',
    icaoCode: 'TUA',
    name: 'Turkmenistan Airlines',
    country: 'Turkmenistan',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'A9',
    icaoCode: 'TGZ',
    name: 'Georgian Airways',
    country: 'Georgia',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: '9U',
    icaoCode: 'MLD',
    name: 'Air Moldova',
    country: 'Moldova',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: '5F',
    icaoCode: 'FIA',
    name: 'FlyOne',
    country: 'Moldova',
    logoUrl: null,
    registrationUrl: 'https://flyone.eu/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'KC',
    icaoCode: 'KZR',
    name: 'Air Astana',
    country: 'Kazakhstan',
    logoUrl: null,
    registrationUrl: 'https://airastana.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 36,
    notes: null,
  },
  {
    iataCode: 'DV',
    icaoCode: 'VSV',
    name: 'SCAT Airlines',
    country: 'Kazakhstan',
    logoUrl: null,
    registrationUrl: '',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'FS',
    icaoCode: 'KFS',
    name: 'FlyArystan',
    country: 'Kazakhstan',
    logoUrl: null,
    registrationUrl: 'https://flyarystan.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
  {
    iataCode: 'IQ',
    icaoCode: 'KZA',
    name: 'Qazaq Air',
    country: 'Kazakhstan',
    logoUrl: null,
    registrationUrl: 'https://flyqazaq.com/check-in',
    supportPhone: '',
    checkInHoursBefore: 24,
    notes: null,
  },
];
